---
- name: 'Demonstrates how to list DataPower class names'
  hosts: dp1
  connection: local

  tasks:
    - name: List all valid configuration objects for the specified domain
      community.datapower.list_objects:
        domain: foo
      register: result

    - name: Assert object list is present
      assert:
        that:
          - "{{ result['objects'] | length != 0 }}"

    - name: List all valid configuration objects for the default domain
      community.datapower.list_objects: